import { useEffect, useState } from 'react';
import Icon from './Icon.jsx';

export default function RecordDialog({ dialog, owners, onClose, onSave }) {
  const [values, setValues] = useState({});
  const [error, setError] = useState('');
  useEffect(() => { setValues({}); setError(''); }, [dialog]);
  if (!dialog) return null;
  const update = e => setValues(current => ({ ...current, [e.target.name]: e.target.value }));
  const save = e => { e.preventDefault(); try { onSave(dialog, values); onClose(); } catch (err) { setError(err.message); } };
  const field = (label, name, options = {}) => <label className={`form-field ${options.wide ? 'wide' : ''}`} key={name}><span>{label}{options.required !== false && <i> *</i>}</span>{options.choices ? <select name={name} required={options.required !== false} value={values[name] || ''} onChange={update}><option value="">Select…</option>{options.choices.map(choice => <option key={choice.value} value={choice.value}>{choice.label}</option>)}</select> : options.multiline ? <textarea name={name} required={options.required !== false} maxLength="180" rows="3" placeholder={options.placeholder} value={values[name] || ''} onChange={update}/> : <input name={name} required={options.required !== false} maxLength="70" placeholder={options.placeholder} value={values[name] || ''} onChange={update}/>}</label>;
  const ownerChoices = owners.map(o => ({ value: o.id, label: `${o.name} · ${o.id}` }));
  let fields;
  if (dialog.type === 'firearm') fields = <>{field('Make', 'make', { placeholder: 'Example Arms' })}{field('Model', 'model', { placeholder: 'Field 12' })}{field('Firearm type', 'type', { choices: ['Rifle', 'Shotgun', 'Other'].map(x => ({ value: x, label: x })) })}{field('Calibre', 'calibre', { placeholder: 'e.g. .22 LR' })}{field('Serial reference', 'serial', { placeholder: 'DEMO-ONLY-0000' })}{field('Category', 'category', { choices: ['Sporting', 'Collection', 'Training'].map(x => ({ value: x, label: x })) })}{field('Linked owner', 'ownerId', { required: false, choices: ownerChoices })}{field('Demo note', 'notes', { required: false, multiline: true, wide: true, placeholder: 'Fictional note only' })}</>;
  else if (dialog.type === 'owner') fields = <>{field('Display name', 'name', { placeholder: 'Fictional person or organisation' })}{field('Owner type', 'kind', { choices: ['Individual', 'Organisation'].map(x => ({ value: x, label: x })) })}{field('Area', 'area', { choices: ['North District', 'South District', 'West District', 'Central District'].map(x => ({ value: x, label: x })) })}{field('Reference', 'reference', { placeholder: 'DEMO-REF-0000' })}<p className="form-hint wide">Use invented names and demonstration references only.</p></>;
  else if (dialog.type === 'status') fields = <><div className="current-value wide"><span>Current status</span><strong>{dialog.record.status}</strong></div>{dialog.record.allowedStatuses.length ? <>{field('New status', 'status', { choices: dialog.record.allowedStatuses.map(x => ({ value: x, label: x })) })}{field('Reason / note', 'note', { multiline: true, wide: true, placeholder: 'Short fictional demo note' })}</> : <p className="form-hint wide">No further status transitions are available for this demo record.</p>}</>;
  else fields = <><div className="current-value wide"><span>Current owner</span><strong>{owners.find(o => o.id === dialog.record.ownerId)?.name || 'Unlinked'}</strong></div>{field('New owner', 'ownerId', { choices: ownerChoices.filter(o => o.value !== dialog.record.ownerId) })}{field('Effective date', 'effectiveDate', { required: false, placeholder: 'e.g. 05 Oct 2026' })}{field('Reason / note', 'note', { multiline: true, wide: true, placeholder: 'Short fictional transfer note' })}</>;
  return <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><section className="record-dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><form onSubmit={save}><div className="dialog-top"><div><span className="section-kicker">{dialog.type === 'firearm' ? 'FIREARM RECORD' : dialog.type === 'owner' ? 'OWNER PROFILE' : `RECORD ${dialog.record.id}`}</span><h2 id="dialog-title">{dialog.title}</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close"><Icon name="close"/></button></div><div className="dialog-fields">{fields}</div>{error && <p className="form-error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" className="button quiet" onClick={onClose}>Cancel</button><button className="button primary" type="submit">Save {dialog.type === 'status' || dialog.type === 'transfer' ? 'change' : 'record'} <Icon name="arrow"/></button></div></form></section></div>;
}
