import { useMemo, useState } from 'react';
import FirearmDetail from '../components/FirearmDetail.jsx';
import OwnerDetail from '../components/OwnerDetail.jsx';
import Sidebar from '../components/Sidebar.jsx';
import Icon from '../components/Icon.jsx';
const statusClass = value => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
function StatusPill({ value }) { return <span className={`status-pill ${statusClass(value)}`}><i/>{value}</span>; }
function FirearmName({ record }) { return <div className="record-name"><span className="record-glyph"><Icon name="registry"/></span><span><strong>{record.displayName}</strong><small>{record.id}</small></span></div>; }
function EmptyState({ title }) { return <div className="empty-state"><Icon name="search"/><strong>{title}</strong><span>Try another search or filter.</span></div>; }

export default function RegistryWorkspace({ state, user, can, setPage, page, onCreate, onSelect, impersonate }) {
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('All statuses');
  const [typeFilter, setTypeFilter] = useState('All types');
  const [categoryFilter, setCategoryFilter] = useState('All categories');
  const [selected, setSelected] = useState(null);
  const [selectedOwner, setSelectedOwner] = useState(null);
  const navigate = nextPage => { setSelected(null); setSelectedOwner(null); setPage(nextPage); };
  const ownersById = useMemo(() => new Map(state.owners.map(o => [o.id, o])), [state.owners]);
  const matching = useMemo(() => state.firearms.filter(r => `${r.id} ${r.displayName} ${r.calibre} ${ownersById.get(r.ownerId)?.name || ''}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'All statuses' || r.status === filter) && (typeFilter === 'All types' || r.type === typeFilter) && (categoryFilter === 'All categories' || r.category === categoryFilter)), [state.firearms, ownersById, search, filter, typeFilter, categoryFilter]);
  if (selected) {
    const record = state.firearms.find(f => f.id === selected);
    if (record) {
      const owner = ownersById.get(record.ownerId);
      const hist = state.ownershipHistory[record.id] || [];
      return <div className="workspace-layout"><Sidebar page={page} setPage={navigate} state={state} user={user} can={can} impersonate={impersonate}/><main className="registry-main"><FirearmDetail record={record} owner={owner ? { ...owner, __allOwners: state.owners } : null} history={hist} events={state.events.filter(e => e.recordId === record.id)} can={can} onBack={() => setSelected(null)} onStatus={() => onSelect(record, 'status')} onTransfer={() => onSelect(record, 'transfer')}/></main></div>;
    }
  }
  if (selectedOwner) {
    const owner = ownersById.get(selectedOwner);
    if (owner) {
      const linked = state.firearms.filter(record => record.ownerId === owner.id);
      const linkedIds = new Set(linked.map(record => record.id));
      const events = state.events.filter(event => linkedIds.has(event.recordId) || event.recordId === owner.id);
      return <div className="workspace-layout"><Sidebar page={page} setPage={navigate} state={state} user={user} can={can} impersonate={impersonate}/><main className="registry-main"><OwnerDetail owner={owner} firearms={linked} events={events} onBack={() => setSelectedOwner(null)} onOpenFirearm={id => { setSelectedOwner(null); setSelected(id); }}/></main></div>;
    }
  }
  const heading = { overview: ['WORKSPACE OVERVIEW', 'Registry overview', 'A current view of fictional records and recent activity.'], firearms: ['RECORDS', 'Firearm register', 'Search and review fictional firearm records.'], owners: ['PEOPLE AND ORGANISATIONS', 'Owner register', 'View fictional owner profiles and linked records.'], activity: ['ACCOUNTABILITY', 'Audit activity', 'Chronological history of changes in this browser.'] }[page];
  const addButton = can('records.create') && page !== 'activity' ? <button className="button primary" onClick={() => onCreate(page === 'owners' ? 'owner' : 'firearm')}><Icon name="add"/> {page === 'owners' ? 'Add owner' : 'Register firearm'}</button> : null;
  const firearmTable = records => <div className="table-scroll"><table className="data-table"><thead><tr><th>FIREARM RECORD</th><th>OWNER</th><th>TYPE / CALIBRE</th><th>STATUS</th><th>LAST UPDATED</th><th/></tr></thead><tbody>{records.map(r => <tr key={r.id} onClick={() => setSelected(r.id)}><td><FirearmName record={r}/></td><td><span className="primary-cell">{ownersById.get(r.ownerId)?.name || 'Unlinked'}</span><small className="secondary-cell">{ownersById.get(r.ownerId)?.id || 'No linked owner'}</small></td><td><span className="primary-cell">{r.type}</span><small className="secondary-cell">{r.calibre}</small></td><td><StatusPill value={r.status}/></td><td className="date-cell">{r.updated}</td><td><button className="row-open" aria-label={`Open ${r.id}`}><Icon name="chevron"/></button></td></tr>)}</tbody></table>{records.length === 0 && <EmptyState title="No records match"/>}</div>;
  return <div className="workspace-layout"><Sidebar page={page} setPage={navigate} state={state} user={user} can={can} impersonate={impersonate}/><main className="registry-main"><div className="breadcrumbs">Demo workspace <span>/</span> {heading[1]}</div><div className="workspace-title"><div><span className="section-kicker">{heading[0]}</span><h1>{heading[1]}</h1><p>{heading[2]}</p></div>{addButton}</div>
    {page === 'overview' && <><div className="metrics-grid"><article><span>TOTAL FIREARMS</span><strong>{state.firearms.length}</strong><small>Fictional registry records</small><i className="metric-symbol teal">▤</i></article><article><span>REGISTERED</span><strong>{state.firearms.filter(x => x.status === 'Registered').length}</strong><small>Active demo status</small><i className="metric-symbol green">✓</i></article><article><span>ATTENTION STATUS</span><strong>{state.firearms.filter(x => x.status === 'Lost / Stolen').length}</strong><small>Lost / stolen records</small><i className="metric-symbol amber">!</i></article><article><span>OWNER PROFILES</span><strong>{state.owners.length}</strong><small>Fictional profiles</small><i className="metric-symbol blue">♙</i></article></div><section className="workspace-panel attention-queue"><div className="panel-heading"><div><h2>Attention queue</h2><p>Records with a lost / stolen demo status</p></div><span className="status-pill lost-stolen"><i/>{state.firearms.filter(x => x.status === 'Lost / Stolen').length} flagged</span></div>{state.firearms.filter(x => x.status === 'Lost / Stolen').length ? state.firearms.filter(x => x.status === 'Lost / Stolen').map(record => <button key={record.id} className="attention-row" onClick={() => setSelected(record.id)}><span className="attention-mark">!</span><span><strong>{record.make} {record.model}</strong><small>{record.id} · {ownersById.get(record.ownerId)?.name || 'Unlinked'} · Updated {record.updated}</small></span><Icon name="chevron"/></button>) : <div className="history-empty">No records currently require attention.</div>}</section><div className="dashboard-columns"><section className="workspace-panel"><div className="panel-heading"><div><h2>Recently updated</h2><p>Recent changes to demo records</p></div><button className="inline-action" onClick={() => setPage('firearms')}>View all <Icon name="arrow"/></button></div>{firearmTable(state.firearms.slice(0, 5))}</section><section className="workspace-panel activity-preview"><div className="panel-heading"><div><h2>Latest activity</h2><p>Local demo history</p></div><button className="inline-action" onClick={() => setPage('activity')}>History <Icon name="arrow"/></button></div><div className="compact-activity">{state.events.slice(0, 4).map(event => <div className="compact-event" key={event.id}><i/><div><strong>{event.action}</strong><span>{event.recordId} · {event.actor}</span></div><small>{event.date}</small></div>)}</div></section></div><div className="notice-strip"><Icon name="shield"/><p><strong>Demonstration safeguards.</strong> Role selection and user preview are simulated in this browser. Nothing here is authenticated or connected to a real registry.</p></div></>}
    {page === 'firearms' && <section className="workspace-panel register-panel"><div className="filter-bar"><label className="search-input"><Icon name="search"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search reference, make, model, calibre or owner"/></label><select value={filter} onChange={e => setFilter(e.target.value)} aria-label="Filter firearm status">{['All statuses', 'Registered', 'Transferred', 'Lost / Stolen', 'Deactivated'].map(s => <option key={s}>{s}</option>)}</select><select value={typeFilter} onChange={e => setTypeFilter(e.target.value)} aria-label="Filter firearm type">{['All types', ...new Set(state.firearms.map(r => r.type))].map(s => <option key={s}>{s}</option>)}</select><select value={categoryFilter} onChange={e => setCategoryFilter(e.target.value)} aria-label="Filter firearm category">{['All categories', ...new Set(state.firearms.map(r => r.category))].map(s => <option key={s}>{s}</option>)}</select><span>{matching.length} records</span></div>{firearmTable(matching)}</section>}
    {page === 'owners' && <section className="workspace-panel register-panel"><div className="filter-bar"><label className="search-input"><Icon name="search"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search names and reference numbers"/></label><span>{state.owners.length} profiles</span></div><div className="table-scroll"><table className="data-table"><thead><tr><th>OWNER</th><th>REFERENCE</th><th>AREA</th><th>LINKED FIREARMS</th><th>LAST UPDATED</th></tr></thead><tbody>{state.owners.filter(o => `${o.name} ${o.reference} ${o.area}`.toLowerCase().includes(search.toLowerCase())).map(o => <tr key={o.id} onClick={() => setSelectedOwner(o.id)}><td><div className="record-name"><span className="owner-glyph">{o.name.split(/\s+/).map(x => x[0]).slice(0, 2).join('')}</span><span><strong>{o.name}</strong><small>{o.kind} · {o.id}</small></span></div></td><td>{o.reference}</td><td>{o.area}</td><td>{state.firearms.filter(f => f.ownerId === o.id).length}</td><td className="date-cell">{o.updated}</td></tr>)}</tbody></table></div></section>}
    {page === 'activity' && <section className="workspace-panel activity-page"><div className="panel-heading"><div><h2>Change history</h2><p>Events stored in this browser only · fictional demonstration</p></div><span className="local-log">LOCAL DEMO LOG</span></div>{state.events.map(event => <article className="audit-event" key={event.id}><span className="audit-icon"><Icon name="history"/></span><div><strong>{event.action}</strong><span className="audit-record">{event.recordId}</span><p>{event.detail}</p><small>Recorded by {event.actor} · {event.id}</small></div><time>{event.date}</time></article>)}</section>}
    <footer className="workspace-footer"><span>Northstar Registry Model</span><span>Fictional data only · Personal project</span>{can('users.preview') && <button onClick={impersonate}>Preview another demo profile</button>}</footer></main></div>;
}
